# Generated by Django 4.2.1 on 2023-07-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0002_fleetuser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='VehiculePaper',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
