# Generated by Django 4.2.1 on 2023-07-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0003_car_vehiculepaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_license',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
