# Generated by Django 4.2.1 on 2023-07-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0004_driver_driver_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='scanContrat',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
