# Generated by Django 4.2.1 on 2023-07-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0005_contract_scancontrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='VehiculePaper',
        ),
    ]
