# Generated by Django 4.2.1 on 2023-07-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0006_remove_car_vehiculepaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='scanContrat',
        ),
    ]
