# Generated by Django 4.2.1 on 2023-08-01 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
        ('core', '0002_create_super_user'),
        ('tenant', '0001_initial'),
        ('fleet_app', '0007_remove_contract_scancontrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutageReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OutageReason',
                'verbose_name_plural': 'OutageReasons',
            },
        ),
        migrations.AlterField(
            model_name='contract',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratVoiture', to='fleet_app.car'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratChauffeur', to='fleet_app.driver'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rest_days',
            field=models.ManyToManyField(related_name='jours', to='core.dayoftheweek'),
        ),
        migrations.CreateModel(
            name='Outages',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance_app.expense')),
                ('location', models.CharField(max_length=100)),
                ('is_okay', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panneVoiture', to='fleet_app.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panneChauffeur', to='fleet_app.driver')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motifPanne', to='fleet_app.outagereason')),
            ],
            options={
                'verbose_name': 'Outage',
                'verbose_name_plural': 'Outages',
            },
            bases=('finance_app.expense',),
        ),
        migrations.CreateModel(
            name='OilChange',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance_app.expense')),
                ('OilType', models.CharField(max_length=100)),
                ('service_center', models.CharField(max_length=100)),
                ('date_OilChange', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitureVidange', to='fleet_app.car')),
            ],
            options={
                'verbose_name': 'OilChange',
                'verbose_name_plural': 'OilChanges',
            },
            bases=('finance_app.expense',),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('insurance_company', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(auto_now=True)),
                ('monthly_amount', models.CharField(max_length=100)),
                ('last_payment', models.IntegerField(default=0)),
                ('next_date', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitureAssurance', to='fleet_app.car')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurances',
            },
        ),
    ]
