# Generated by Django 4.2.1 on 2023-08-06 14:01

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0008_outagereason_alter_contract_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name_slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='model', unique_with=['id', 'date_add']),
            preserve_default=False,
        ),
    ]
