# Generated by Django 4.2.1 on 2023-08-11 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('fleet_app', '0009_car_name_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('date_payment', models.DateField(default=django.utils.timezone.now)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InsurancePayment', to='fleet_app.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'InsurancePayment',
                'verbose_name_plural': 'InsurancePayments',
            },
        ),
    ]
