# Generated by Django 4.2.1 on 2023-08-11 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0010_insurancepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilchange',
            name='date_next_oil_change',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
