# Generated by Django 4.2.1 on 2023-08-16 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
        ('fleet_app', '0011_oilchange_date_next_oil_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance_app.expense')),
                ('location', models.CharField(max_length=100)),
                ('is_okay', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outages', to='fleet_app.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outages', to='fleet_app.driver')),
            ],
            options={
                'verbose_name': 'Outage',
                'verbose_name_plural': 'Outages',
            },
            bases=('finance_app.expense',),
        ),
        migrations.RenameField(
            model_name='oilchange',
            old_name='OilType',
            new_name='oil_type',
        ),
        migrations.AddField(
            model_name='outagereason',
            name='statut',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Outages',
        ),
        migrations.AddField(
            model_name='outage',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outages', to='fleet_app.outagereason'),
        ),
    ]
