# Generated by Django 4.2.1 on 2023-08-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_rename_payment_method_expense_payment_method_and_more'),
        ('fleet_app', '0013_alter_insurance_monthly_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='insurancepayment',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='insurancepayment',
            name='date_payment',
        ),
        migrations.RemoveField(
            model_name='insurancepayment',
            name='date_upd',
        ),
        migrations.RemoveField(
            model_name='insurancepayment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='insurancepayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='insurancepayment',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='insurancepayment',
            name='tenant',
        ),
        migrations.AddField(
            model_name='insurancepayment',
            name='expense_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance_app.expense'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancepayment',
            name='insurance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fleet_app.insurance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurance',
            name='monthly_amount',
            field=models.IntegerField(),
        ),
    ]
