# Generated by Django 4.2.1 on 2023-08-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0015_alter_outage_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetuser',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
