# Generated by Django 4.2.1 on 2023-09-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0016_fleetuser_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetuser',
            name='token_forget_password',
            field=models.CharField(default=14, max_length=100),
            preserve_default=False,
        ),
    ]
