# Generated by Django 4.2.1 on 2023-09-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0017_fleetuser_token_forget_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetuser',
            name='token_forget_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
