version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./docker-entrypoint.dev.sh
    volumes:
      - .:/usr/src/app
      - media_files_dev:/usr/src/app/media_cdn
    ports:
      - "8000:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FLEET

  cache:
    image: redis:6.2.6-alpine
    volumes:
      - redis_data_dev:/var/lib/redis
      - redis_conf_dev:/usr/local/etc/redis/redis.conf


volumes:
  postgres_data_dev:
  media_files_dev:
  redis_data_dev:
  redis_conf_dev: