version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./docker-entrypoint.sh
    volumes:
      - fleet_media_files:/usr/src/app/media_cdn
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./docker/postgres/.env.prod
    ports:
      - "35432:5432"
    restart: unless-stopped

  cache:
    image: redis:6.2.6-alpine
    volumes:
      - redis_data:/var/lib/redis
      - redis_conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped

  nginx:
    depends_on:
      - web
      - db
      - cache
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./docker/nginx
    ports:
      - "6500:80"
    volumes:
      - fleet_media_files:/usr/src/app/media_cdn
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  fleet_media_files:
    external: true
  redis_data:
  redis_conf: