# Generated by Django 4.2.1 on 2023-05-22 15:14

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', core.fields.DayOfTheWeekField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
            ],
            options={
                'verbose_name': 'DayOfTheWeek',
                'verbose_name_plural': 'DayOfTheWeeks',
            },
        ),
    ]
