# Generated by Django 4.2.1 on 2023-08-10 17:33

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_day_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoftheweek',
            name='day',
            field=core.fields.DayOfTheWeekField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], unique=True),
        ),
    ]
