# Generated by Django 4.2.1 on 2025-08-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
    ]
