# Generated by Django 4.2.1 on 2023-08-16 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Payment_Method',
            new_name='payment_method',
        ),
        migrations.AddField(
            model_name='expense',
            name='date_payment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
